workspace:
  subscription_id: ${AZURE_SUBSCRIPTION_ID}
  resource_group: ${AZURE_RESOURCE_GROUP}
  workspace_name: ${AZURE_WORKSPACE_NAME}

environment:
  name: log_generate
  version: latest

compute:
  compute_cluster: training-gpu

pipeline:
  experiment_name: llm-tuning

data:
  name: azureml:zoo_asset:1
  output_asset_name: zookeeper_transformed

hfmodel:
  name: azureml:hf_qwen_model:1
